'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import {
  Wand2,
  FileText,
  ClipboardList,
  BarChart3,
  Download,
  Edit,
  Copy,
  Loader2,
  Sparkles,
  BookOpen,
  CheckCircle2,
  AlertCircle,
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface GeneratedContent {
  type: 'lesson' | 'quiz' | 'report';
  title: string;
  content: string;
  metadata: {
    subject: string;
    grade: string;
    topic: string;
    difficulty?: string;
    duration?: string;
  };
  generatedAt: string;
}

interface MagicSchoolAIProps {
  className?: string;
}

const CBC_GRADES = [
  'Grade 1',
  'Grade 2',
  'Grade 3',
  'Grade 4',
  'Grade 5',
  'Grade 6',
  'Grade 7',
  'Grade 8',
  'Grade 9',
];

const SUBJECTS = [
  'Mathematics',
  'English',
  'Kiswahili',
  'Science',
  'Social Studies',
  'Religious Education',
  'Creative Arts',
  'Physical Education',
];

const DIFFICULTY_LEVELS = ['Easy', 'Medium', 'Hard', 'Mixed'];

export function MagicSchoolAI({ className }: MagicSchoolAIProps) {
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<GeneratedContent | null>(null);

  // Lesson Plan Form
  const [lessonTopic, setLessonTopic] = useState('');
  const [lessonGrade, setLessonGrade] = useState('');
  const [lessonSubject, setLessonSubject] = useState('');
  const [lessonDuration, setLessonDuration] = useState('40');
  const [lessonObjectives, setLessonObjectives] = useState('');

  // Quiz Form
  const [quizTopic, setQuizTopic] = useState('');
  const [quizGrade, setQuizGrade] = useState('');
  const [quizSubject, setQuizSubject] = useState('');
  const [quizDifficulty, setQuizDifficulty] = useState('');
  const [quizQuestions, setQuizQuestions] = useState('10');

  // Report Form
  const [reportStudentId, setReportStudentId] = useState('');
  const [reportType, setReportType] = useState('progress');
  const [reportPeriod, setReportPeriod] = useState('term');

  const generateLessonPlan = async () => {
    if (!lessonTopic || !lessonGrade || !lessonSubject) {
      toast({
        title: 'Missing Information',
        description: 'Please fill in all required fields',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      // Simulate API call - replace with actual backend call
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const content = `# Lesson Plan: ${lessonTopic}

**Subject:** ${lessonSubject}
**Grade:** ${lessonGrade}
**Duration:** ${lessonDuration} minutes

## Learning Objectives
${lessonObjectives || '- Students will understand the key concepts of ' + lessonTopic}

## Materials Needed
- Textbooks
- Whiteboard and markers
- Student notebooks
- Visual aids (charts, diagrams)

## Lesson Structure

### Introduction (10 minutes)
- Greet students and review previous lesson
- Introduce today's topic: ${lessonTopic}
- Ask engaging questions to activate prior knowledge

### Main Activity (20 minutes)
- Explain key concepts with examples
- Use visual aids to demonstrate
- Encourage student participation through questions
- Provide real-world Kenyan context examples

### Practice (5 minutes)
- Students work on guided practice problems
- Teacher circulates to provide support
- Address common misconceptions

### Conclusion (5 minutes)
- Recap main points
- Ask students to share what they learned
- Assign homework for reinforcement

## Assessment
- Observe student participation
- Check understanding through questioning
- Review practice work

## Differentiation
- Provide extra support for struggling learners
- Offer extension activities for advanced students
- Use multiple modalities (visual, auditory, kinesthetic)

## Homework
- Practice exercises from textbook pages X-Y
- Prepare questions for next lesson

---
*Generated by syncsenta Magic School*
*Aligned with CBC curriculum for ${lessonGrade}*
`;

      setGeneratedContent({
        type: 'lesson',
        title: `Lesson Plan: ${lessonTopic}`,
        content,
        metadata: {
          subject: lessonSubject,
          grade: lessonGrade,
          topic: lessonTopic,
          duration: lessonDuration + ' minutes',
        },
        generatedAt: new Date().toISOString(),
      });

      toast({
        title: 'Lesson Plan Generated!',
        description: 'Your lesson plan is ready to use',
      });
    } catch (error) {
      toast({
        title: 'Generation Failed',
        description: 'Failed to generate lesson plan. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const generateQuiz = async () => {
    if (!quizTopic || !quizGrade || !quizSubject || !quizDifficulty) {
      toast({
        title: 'Missing Information',
        description: 'Please fill in all required fields',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const content = `# Quiz: ${quizTopic}

**Subject:** ${quizSubject}
**Grade:** ${quizGrade}
**Difficulty:** ${quizDifficulty}
**Total Questions:** ${quizQuestions}

## Instructions
- Read each question carefully
- Choose the best answer
- Show your working where required
- Time limit: ${parseInt(quizQuestions) * 2} minutes

---

## Questions

${Array.from({ length: parseInt(quizQuestions) }, (_, i) => `
### Question ${i + 1}
[Question about ${quizTopic} - ${quizDifficulty} level]

A) Option A
B) Option B
C) Option C
D) Option D

**Answer:** [Correct answer]
**Explanation:** [Brief explanation of why this is correct]

---
`).join('\n')}

## Marking Scheme
- Each question: ${100 / parseInt(quizQuestions)} marks
- Total: 100 marks
- Pass mark: 50 marks

## Learning Outcomes Assessed
- Understanding of ${quizTopic}
- Application of concepts
- Problem-solving skills

---
*Generated by syncsenta Magic School*
*CBC-aligned assessment for ${quizGrade}*
`;

      setGeneratedContent({
        type: 'quiz',
        title: `Quiz: ${quizTopic}`,
        content,
        metadata: {
          subject: quizSubject,
          grade: quizGrade,
          topic: quizTopic,
          difficulty: quizDifficulty,
        },
        generatedAt: new Date().toISOString(),
      });

      toast({
        title: 'Quiz Generated!',
        description: `${quizQuestions} questions ready for your students`,
      });
    } catch (error) {
      toast({
        title: 'Generation Failed',
        description: 'Failed to generate quiz. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const generateReport = async () => {
    if (!reportStudentId) {
      toast({
        title: 'Missing Information',
        description: 'Please enter a student ID',
        variant: 'destructive',
      });
      return;
    }

    setIsGenerating(true);
    try {
      await new Promise((resolve) => setTimeout(resolve, 2000));

      const content = `# Student Progress Report

**Student ID:** ${reportStudentId}
**Report Type:** ${reportType === 'progress' ? 'Progress Report' : 'Performance Summary'}
**Period:** ${reportPeriod === 'term' ? 'Term' : reportPeriod === 'month' ? 'Monthly' : 'Weekly'}
**Generated:** ${new Date().toLocaleDateString()}

---

## Academic Performance

### Mathematics
- **Current Grade:** B+
- **Mastery:** 78%
- **Strengths:** Problem-solving, fractions
- **Areas for Improvement:** Word problems, geometry
- **Recommendation:** Additional practice with real-world applications

### English
- **Current Grade:** A-
- **Mastery:** 85%
- **Strengths:** Reading comprehension, vocabulary
- **Areas for Improvement:** Essay structure
- **Recommendation:** Focus on paragraph organization

### Science
- **Current Grade:** B
- **Mastery:** 72%
- **Strengths:** Observation skills, curiosity
- **Areas for Improvement:** Scientific method, lab reports
- **Recommendation:** More hands-on experiments

---

## Learning Behavior

- **Attendance:** 95% (Excellent)
- **Participation:** Active and engaged
- **Homework Completion:** 90%
- **Collaboration:** Works well with peers

---

## AI Tutor Insights (syncsenta)

- **Total Sessions:** 45
- **Average Session Time:** 25 minutes
- **Learning Streak:** 12 days
- **Emotional State:** Mostly engaged and confident
- **Preferred Learning Style:** Visual learner

---

## Teacher Comments

Student shows consistent effort and improvement across all subjects. Demonstrates strong curiosity and willingness to learn. Recommended to continue current learning path with additional support in identified weak areas.

---

## Recommendations for Parents

1. Encourage daily reading for 20 minutes
2. Practice mathematics word problems together
3. Discuss science topics from daily life
4. Maintain consistent study schedule
5. Celebrate achievements and progress

---

## Next Steps

- Schedule parent-teacher conference
- Provide additional resources for weak areas
- Continue monitoring progress through syncsenta
- Set goals for next ${reportPeriod}

---
*Generated by syncsenta Magic School*
*Data-driven insights for personalized learning*
`;

      setGeneratedContent({
        type: 'report',
        title: `Progress Report - Student ${reportStudentId}`,
        content,
        metadata: {
          subject: 'All Subjects',
          grade: 'N/A',
          topic: reportType,
        },
        generatedAt: new Date().toISOString(),
      });

      toast({
        title: 'Report Generated!',
        description: 'Student progress report is ready',
      });
    } catch (error) {
      toast({
        title: 'Generation Failed',
        description: 'Failed to generate report. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadContent = () => {
    if (!generatedContent) return;

    const blob = new Blob([generatedContent.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${generatedContent.title.replace(/[^a-z0-9]/gi, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: 'Downloaded!',
      description: 'Content saved to your device',
    });
  };

  const copyContent = () => {
    if (!generatedContent) return;

    navigator.clipboard.writeText(generatedContent.content);
    toast({
      title: 'Copied!',
      description: 'Content copied to clipboard',
    });
  };

  return (
    <div className={cn('space-y-6', className)}>
      <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950 dark:to-indigo-950 border-blue-200 dark:border-blue-800">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-blue-700 dark:text-blue-300">
            <Wand2 className="h-6 w-6" />
            Magic School AI
          </CardTitle>
          <CardDescription className="text-blue-600 dark:text-blue-400">
            Auto-generate lessons, quizzes, and reports with AI - inspired by Magic School AI
          </CardDescription>
        </CardHeader>
      </Card>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Generation Forms */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5" />
              Generate Content
            </CardTitle>
            <CardDescription>Choose what you want to create</CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="lesson" className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="lesson" className="gap-1">
                  <FileText className="h-4 w-4" />
                  Lesson
                </TabsTrigger>
                <TabsTrigger value="quiz" className="gap-1">
                  <ClipboardList className="h-4 w-4" />
                  Quiz
                </TabsTrigger>
                <TabsTrigger value="report" className="gap-1">
                  <BarChart3 className="h-4 w-4" />
                  Report
                </TabsTrigger>
              </TabsList>

              {/* Lesson Plan Form */}
              <TabsContent value="lesson" className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="lesson-topic">Topic *</Label>
                  <Input
                    id="lesson-topic"
                    placeholder="e.g., Fractions and Decimals"
                    value={lessonTopic}
                    onChange={(e) => setLessonTopic(e.target.value)}
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="lesson-grade">Grade *</Label>
                    <Select value={lessonGrade} onValueChange={setLessonGrade}>
                      <SelectTrigger id="lesson-grade">
                        <SelectValue placeholder="Select grade" />
                      </SelectTrigger>
                      <SelectContent>
                        {CBC_GRADES.map((grade) => (
                          <SelectItem key={grade} value={grade}>
                            {grade}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="lesson-subject">Subject *</Label>
                    <Select value={lessonSubject} onValueChange={setLessonSubject}>
                      <SelectTrigger id="lesson-subject">
                        <SelectValue placeholder="Select subject" />
                      </SelectTrigger>
                      <SelectContent>
                        {SUBJECTS.map((subject) => (
                          <SelectItem key={subject} value={subject}>
                            {subject}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lesson-duration">Duration (minutes)</Label>
                  <Input
                    id="lesson-duration"
                    type="number"
                    value={lessonDuration}
                    onChange={(e) => setLessonDuration(e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="lesson-objectives">Learning Objectives (optional)</Label>
                  <Textarea
                    id="lesson-objectives"
                    placeholder="What should students learn?"
                    value={lessonObjectives}
                    onChange={(e) => setLessonObjectives(e.target.value)}
                    rows={3}
                  />
                </div>
                <Button
                  onClick={generateLessonPlan}
                  disabled={isGenerating}
                  className="w-full"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2 className="mr-2 h-4 w-4" />
                      Generate Lesson Plan
                    </>
                  )}
                </Button>
              </TabsContent>

              {/* Quiz Form */}
              <TabsContent value="quiz" className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="quiz-topic">Topic *</Label>
                  <Input
                    id="quiz-topic"
                    placeholder="e.g., Photosynthesis"
                    value={quizTopic}
                    onChange={(e) => setQuizTopic(e.target.value)}
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="quiz-grade">Grade *</Label>
                    <Select value={quizGrade} onValueChange={setQuizGrade}>
                      <SelectTrigger id="quiz-grade">
                        <SelectValue placeholder="Select grade" />
                      </SelectTrigger>
                      <SelectContent>
                        {CBC_GRADES.map((grade) => (
                          <SelectItem key={grade} value={grade}>
                            {grade}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="quiz-subject">Subject *</Label>
                    <Select value={quizSubject} onValueChange={setQuizSubject}>
                      <SelectTrigger id="quiz-subject">
                        <SelectValue placeholder="Select subject" />
                      </SelectTrigger>
                      <SelectContent>
                        {SUBJECTS.map((subject) => (
                          <SelectItem key={subject} value={subject}>
                            {subject}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="quiz-difficulty">Difficulty *</Label>
                    <Select value={quizDifficulty} onValueChange={setQuizDifficulty}>
                      <SelectTrigger id="quiz-difficulty">
                        <SelectValue placeholder="Select difficulty" />
                      </SelectTrigger>
                      <SelectContent>
                        {DIFFICULTY_LEVELS.map((level) => (
                          <SelectItem key={level} value={level}>
                            {level}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="quiz-questions">Number of Questions</Label>
                    <Input
                      id="quiz-questions"
                      type="number"
                      value={quizQuestions}
                      onChange={(e) => setQuizQuestions(e.target.value)}
                      min="5"
                      max="50"
                    />
                  </div>
                </div>
                <Button onClick={generateQuiz} disabled={isGenerating} className="w-full">
                  {isGenerating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2 className="mr-2 h-4 w-4" />
                      Generate Quiz
                    </>
                  )}
                </Button>
              </TabsContent>

              {/* Report Form */}
              <TabsContent value="report" className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="report-student">Student ID *</Label>
                  <Input
                    id="report-student"
                    placeholder="Enter student ID"
                    value={reportStudentId}
                    onChange={(e) => setReportStudentId(e.target.value)}
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="report-type">Report Type</Label>
                    <Select value={reportType} onValueChange={setReportType}>
                      <SelectTrigger id="report-type">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="progress">Progress Report</SelectItem>
                        <SelectItem value="performance">Performance Summary</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="report-period">Period</Label>
                    <Select value={reportPeriod} onValueChange={setReportPeriod}>
                      <SelectTrigger id="report-period">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="week">Weekly</SelectItem>
                        <SelectItem value="month">Monthly</SelectItem>
                        <SelectItem value="term">Term</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <Button onClick={generateReport} disabled={isGenerating} className="w-full">
                  {isGenerating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2 className="mr-2 h-4 w-4" />
                      Generate Report
                    </>
                  )}
                </Button>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>

        {/* Generated Content Preview */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="h-5 w-5" />
              Generated Content
            </CardTitle>
            <CardDescription>
              {generatedContent ? 'Preview and download your content' : 'Content will appear here'}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {generatedContent ? (
              <div className="space-y-4">
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <h3 className="font-semibold">{generatedContent.title}</h3>
                    <div className="flex flex-wrap gap-2 mt-2">
                      <Badge variant="secondary">{generatedContent.metadata.subject}</Badge>
                      <Badge variant="outline">{generatedContent.metadata.grade}</Badge>
                      {generatedContent.metadata.difficulty && (
                        <Badge variant="outline">{generatedContent.metadata.difficulty}</Badge>
                      )}
                    </div>
                  </div>
                  <Badge variant="default" className="gap-1">
                    <CheckCircle2 className="h-3 w-3" />
                    Ready
                  </Badge>
                </div>

                <div className="bg-muted p-4 rounded-lg max-h-[400px] overflow-y-auto">
                  <pre className="text-xs whitespace-pre-wrap font-mono">
                    {generatedContent.content}
                  </pre>
                </div>

                <div className="flex gap-2">
                  <Button onClick={downloadContent} className="flex-1">
                    <Download className="mr-2 h-4 w-4" />
                    Download
                  </Button>
                  <Button onClick={copyContent} variant="outline" className="flex-1">
                    <Copy className="mr-2 h-4 w-4" />
                    Copy
                  </Button>
                  <Button variant="outline" size="icon">
                    <Edit className="h-4 w-4" />
                  </Button>
                </div>

                <p className="text-xs text-muted-foreground text-center">
                  Generated {new Date(generatedContent.generatedAt).toLocaleString()}
                </p>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <AlertCircle className="h-12 w-12 text-muted-foreground mb-4" />
                <p className="text-sm text-muted-foreground">
                  Fill in the form and click generate to create content
                </p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
